name: Deploy Frontend to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH for deployment
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and restart on server
        run: |
          ssh -o StrictHostKeyChecking=no root@194.164.149.238 << 'EOF'
            cd /root/wribate-frontend
            git fetch --all
            git reset --hard origin/main
            npm install
            npm run build
            pm2 restart frontend || pm2 start npm --name frontend -- start
          EOF
